apiVersion: v1
kind: Pod
metadata:
  name: ansible-node2
  namespace: ansible
spec:
  containers:
  - name: node
    image: kunal0816/ansible-node:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 22
  restartPolicy: Never
