apiVersion: v1
kind: Pod
metadata:
  name: ansible-master
  namespace: ansible
spec:
  containers:
  - name: master
    image: kunal0816/ansible-master:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 22
  restartPolicy: Never
